In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

# numpy 

In [7]:
x=np.array([1,2,3,4])
y=np.array([1,2,5])



In [8]:
x

array([1, 2, 3, 4])

In [9]:
y

array([1, 2, 5])

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
x=np.array([[1,2,3,4],[2,3,4,5]])

In [12]:
x

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [13]:
x.shape

(2, 4)

In [16]:
x=np.array([[1,2],[2,4]])
y=np.array([[1,5],[2,1]])

In [17]:
x+y

array([[2, 7],
       [4, 5]])

In [18]:
x-y

array([[ 0, -3],
       [ 0,  3]])

In [19]:
x*y

array([[ 1, 10],
       [ 4,  4]])

In [20]:
x/y

array([[1. , 0.4],
       [1. , 4. ]])

In [21]:
x**y

array([[ 1, 32],
       [ 4,  4]])

In [22]:
x ,y

(array([[1, 2],
        [2, 4]]),
 array([[1, 5],
        [2, 1]]))

In [25]:
x.shape

(2, 2)

In [26]:
y.shape

(2, 2)

In [23]:
np.matmul(x,y)

array([[ 5,  7],
       [10, 14]])

In [24]:
x**2

array([[ 1,  4],
       [ 4, 16]])

In [ ]:
# rows/cols of first one === rows/cols of second one [ add sub]
# cols of first one === rows of second one [ mul]

In [ ]:
x**2 

np.matmul(x,x)

# indexing

In [27]:
x

array([[1, 2],
       [2, 4]])

In [28]:
x[1,1]

4

In [31]:
x[:,1]

array([2, 4])

In [32]:
x[:,0]

array([1, 2])

# math

In [33]:
np.sin(0)

0.0

In [34]:
np.cos(0)


1.0

In [35]:
np.tan(0)

0.0

In [37]:
np.exp(2)

7.38905609893065

In [39]:
np.log10(100)

2.0

In [40]:
np.log10(1000)


3.0

# custom arrays

In [42]:
x=np.zeros((8,8))  # 

In [44]:
y=np.ones((10,10))


In [46]:
x 

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
x[0:-1:2,0:-1:2]=1

In [48]:
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# array operations 

In [50]:
x=np.array([[1,2,3],[2,9,0],[3,9,8]])

In [51]:
x

array([[1, 2, 3],
       [2, 9, 0],
       [3, 9, 8]])

In [58]:
np.max(x,axis=1)

array([3, 9, 9])

In [59]:
np.min(x,axis=1)

array([1, 0, 3])

In [60]:
np.var(x,axis=1)

array([ 0.66666667, 14.88888889,  6.88888889])

In [61]:
np.std(x,axis=1)

array([0.81649658, 3.8586123 , 2.62466929])

In [62]:
np.median(x,axis=1)

array([2., 2., 8.])

# Concat

In [63]:
x

array([[1, 2, 3],
       [2, 9, 0],
       [3, 9, 8]])

In [64]:
y=x+10

In [65]:
y

array([[11, 12, 13],
       [12, 19, 10],
       [13, 19, 18]])

In [70]:
np.concatenate([x,y],axis=0)


array([[ 1,  2,  3],
       [ 2,  9,  0],
       [ 3,  9,  8],
       [11, 12, 13],
       [12, 19, 10],
       [13, 19, 18]])

In [69]:
np.concatenate([x,y],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 2,  9,  0, 12, 19, 10],
       [ 3,  9,  8, 13, 19, 18]])

# Matrix soltuions 

In [71]:
'''

2x+3y=10

3x+7y=20



'''

'\n\n2x+3y=10\n\n3x+7y=20\n\n\n\n'

In [72]:
np.linalg.solve([[2,3],[3,7]]  , [10,20])

array([2., 2.])